version: '3'
services:
  web:
    container_name: image_retrieval_api
    build: .
    restart: always
    volumes:
      - .:/code
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count:  1
              capabilities: [gpu]
    networks:
      mynet:
        ipv4_address: 10.5.0.4
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:24.01-py3
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./models:/models
    command: ["tritonserver", "--model-repository=/models", "--log-verbose", "1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count:  1
              capabilities: [gpu]
    networks:
      mynet:
        ipv4_address: 10.5.0.5
networks:
  mynet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
